// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_space_oneK_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'space_oneK', line 30, column 1 to column 22)",
                                                      " (in 'space_oneK', line 31, column 1 to column 22)",
                                                      " (in 'space_oneK', line 32, column 1 to column 32)",
                                                      " (in 'space_oneK', line 33, column 1 to column 21)",
                                                      " (in 'space_oneK', line 34, column 3 to column 29)",
                                                      " (in 'space_oneK', line 37, column 1 to column 20)",
                                                      " (in 'space_oneK', line 38, column 1 to column 67)",
                                                      " (in 'space_oneK', line 41, column 1 to column 22)",
                                                      " (in 'space_oneK', line 42, column 1 to column 22)",
                                                      " (in 'space_oneK', line 43, column 1 to column 23)",
                                                      " (in 'space_oneK', line 44, column 1 to column 22)",
                                                      " (in 'space_oneK', line 45, column 1 to column 34)",
                                                      " (in 'space_oneK', line 46, column 1 to column 29)",
                                                      " (in 'space_oneK', line 18, column 1 to column 16)",
                                                      " (in 'space_oneK', line 19, column 1 to column 16)",
                                                      " (in 'space_oneK', line 20, column 1 to column 18)",
                                                      " (in 'space_oneK', line 21, column 8 to column 9)",
                                                      " (in 'space_oneK', line 21, column 10 to column 11)",
                                                      " (in 'space_oneK', line 21, column 1 to column 20)",
                                                      " (in 'space_oneK', line 22, column 8 to column 9)",
                                                      " (in 'space_oneK', line 22, column 11 to column 12)",
                                                      " (in 'space_oneK', line 22, column 1 to column 22)",
                                                      " (in 'space_oneK', line 23, column 1 to column 19)",
                                                      " (in 'space_oneK', line 26, column 8 to column 9)",
                                                      " (in 'space_oneK', line 26, column 10 to column 11)",
                                                      " (in 'space_oneK', line 26, column 1 to column 21)",
                                                      " (in 'space_oneK', line 27, column 1 to column 23)",
                                                      " (in 'space_oneK', line 34, column 19 to column 20)",
                                                      " (in 'space_oneK', line 37, column 8 to column 9)",
                                                      " (in 'space_oneK', line 37, column 10 to column 11)",
                                                      " (in 'space_oneK', line 3, column 9 to column 10)",
                                                      " (in 'space_oneK', line 3, column 11 to column 12)",
                                                      " (in 'space_oneK', line 3, column 2 to column 21)",
                                                      " (in 'space_oneK', line 4, column 9 to column 10)",
                                                      " (in 'space_oneK', line 4, column 11 to column 12)",
                                                      " (in 'space_oneK', line 4, column 2 to column 22)",
                                                      " (in 'space_oneK', line 5, column 2 to column 29)",
                                                      " (in 'space_oneK', line 6, column 2 to column 32)",
                                                      " (in 'space_oneK', line 9, column 4 to column 47)",
                                                      " (in 'space_oneK', line 10, column 4 to column 30)",
                                                      " (in 'space_oneK', line 8, column 16 to line 11, column 4)",
                                                      " (in 'space_oneK', line 8, column 3 to line 11, column 4)",
                                                      " (in 'space_oneK', line 7, column 15 to line 12, column 3)",
                                                      " (in 'space_oneK', line 7, column 2 to line 12, column 3)",
                                                      " (in 'space_oneK', line 13, column 2 to column 28)",
                                                      " (in 'space_oneK', line 14, column 2 to column 16)",
                                                      " (in 'space_oneK', line 2, column 85 to line 15, column 2)"};
template <typename T1__, typename T2__, typename T3__, typename T4__,
typename T5__, typename T6__>
Eigen::Matrix<stan::promote_args_t<T1__, T2__, T3__, stan::value_type_t<T4__>,
stan::value_type_t<T5__>, stan::promote_args_t<T6__>>, -1, -1>
spCov(const int& N, const T1__& a0, const T2__& aD, const T3__& a2,
      const T4__& D_arg__, const T5__& nugget_arg__, const T6__& gamma,
      std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T1__,
          T2__,
          T3__,
          stan::value_type_t<T4__>,
          stan::value_type_t<T5__>, stan::promote_args_t<T6__>>;
  const auto& D = to_ref(D_arg__);
  const auto& nugget = to_ref(nugget_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 31;
    validate_non_negative_index("parCov", "N", N);
    current_statement__ = 32;
    validate_non_negative_index("parCov", "N", N);
    Eigen::Matrix<local_scalar_t__, -1, -1> parCov;
    parCov = Eigen::Matrix<local_scalar_t__, -1, -1>(N, N);
    stan::math::fill(parCov, DUMMY_VAR__);
    
    current_statement__ = 34;
    validate_non_negative_index("Nug_mat", "N", N);
    current_statement__ = 35;
    validate_non_negative_index("Nug_mat", "N", N);
    Eigen::Matrix<local_scalar_t__, -1, -1> Nug_mat;
    Nug_mat = Eigen::Matrix<local_scalar_t__, -1, -1>(N, N);
    stan::math::fill(Nug_mat, DUMMY_VAR__);
    
    current_statement__ = 37;
    assign(parCov, nil_index_list(), rep_matrix(0, N, N),
      "assigning variable parCov");
    current_statement__ = 38;
    assign(Nug_mat, nil_index_list(), diag_matrix(nugget),
      "assigning variable Nug_mat");
    current_statement__ = 44;
    for (int i = 1; i <= N; ++i) {
      current_statement__ = 42;
      for (int j = i; j <= N; ++j) {
        current_statement__ = 39;
        assign(parCov,
          cons_list(index_uni(i), cons_list(index_uni(j), nil_index_list())),
          (a0 *
            stan::math::exp(
              -pow(
                 (aD *
                   rvalue(D,
                     cons_list(index_uni(i),
                       cons_list(index_uni(j), nil_index_list())), "D")), a2))),
          "assigning variable parCov");
        current_statement__ = 40;
        assign(parCov,
          cons_list(index_uni(j), cons_list(index_uni(i), nil_index_list())),
          rvalue(parCov,
            cons_list(index_uni(i),
              cons_list(index_uni(j), nil_index_list())), "parCov"),
          "assigning variable parCov");}}
    current_statement__ = 45;
    assign(parCov, nil_index_list(),
      add(stan::model::deep_copy(parCov), add(gamma, Nug_mat)),
      "assigning variable parCov");
    current_statement__ = 46;
    return parCov;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct spCov_functor__ {
template <typename T1__, typename T2__, typename T3__, typename T4__,
typename T5__, typename T6__>
Eigen::Matrix<stan::promote_args_t<T1__, T2__, T3__, stan::value_type_t<T4__>,
stan::value_type_t<T5__>, stan::promote_args_t<T6__>>, -1, -1>
operator()(const int& N, const T1__& a0, const T2__& aD, const T3__& a2,
           const T4__& D, const T5__& nugget, const T6__& gamma,
           std::ostream* pstream__)  const 
{
return spCov(N, a0, aD, a2, D, nugget, gamma, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_space_oneK final : public model_base_crtp<model_space_oneK> {
private:
  int K;
  int N;
  int L;
  Eigen::Matrix<double, -1, -1> obsCov;
  Eigen::Matrix<double, -1, -1> geoDist;
  double varMeanFreqs;
  Eigen::Matrix<double, -1, -1> LobsCov;
 
public:
  ~model_space_oneK() { }
  
  inline std::string model_name() const final { return "model_space_oneK"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_space_oneK(stan::io::var_context& context__,
                   unsigned int random_seed__ = 0,
                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_space_oneK_namespace::model_space_oneK";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","K","int",
          context__.to_vec());
      K = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 14;
      current_statement__ = 14;
      check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 15;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 15;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 15;
      current_statement__ = 15;
      check_greater_or_equal(function__, "N", N, 2);
      current_statement__ = 16;
      context__.validate_dims("data initialization","L","int",
          context__.to_vec());
      L = std::numeric_limits<int>::min();
      
      current_statement__ = 16;
      L = context__.vals_i("L")[(1 - 1)];
      current_statement__ = 16;
      current_statement__ = 16;
      check_greater_or_equal(function__, "L", L, (N + 1));
      current_statement__ = 17;
      validate_non_negative_index("obsCov", "N", N);
      current_statement__ = 18;
      validate_non_negative_index("obsCov", "N", N);
      current_statement__ = 19;
      context__.validate_dims("data initialization","obsCov","double",
          context__.to_vec(N, N));
      obsCov = Eigen::Matrix<double, -1, -1>(N, N);
      stan::math::fill(obsCov, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> obsCov_flat__;
        current_statement__ = 19;
        assign(obsCov_flat__, nil_index_list(), context__.vals_r("obsCov"),
          "assigning variable obsCov_flat__");
        current_statement__ = 19;
        pos__ = 1;
        current_statement__ = 19;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 19;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 19;
            assign(obsCov,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              obsCov_flat__[(pos__ - 1)], "assigning variable obsCov");
            current_statement__ = 19;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 20;
      validate_non_negative_index("geoDist", "N", N);
      current_statement__ = 21;
      validate_non_negative_index("geoDist", "N", N);
      current_statement__ = 22;
      context__.validate_dims("data initialization","geoDist","double",
          context__.to_vec(N, N));
      geoDist = Eigen::Matrix<double, -1, -1>(N, N);
      stan::math::fill(geoDist, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> geoDist_flat__;
        current_statement__ = 22;
        assign(geoDist_flat__, nil_index_list(), context__.vals_r("geoDist"),
          "assigning variable geoDist_flat__");
        current_statement__ = 22;
        pos__ = 1;
        current_statement__ = 22;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 22;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 22;
            assign(geoDist,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              geoDist_flat__[(pos__ - 1)], "assigning variable geoDist");
            current_statement__ = 22;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 23;
      context__.validate_dims("data initialization","varMeanFreqs","double",
          context__.to_vec());
      varMeanFreqs = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 23;
      varMeanFreqs = context__.vals_r("varMeanFreqs")[(1 - 1)];
      current_statement__ = 24;
      validate_non_negative_index("LobsCov", "N", N);
      current_statement__ = 25;
      validate_non_negative_index("LobsCov", "N", N);
      current_statement__ = 26;
      LobsCov = Eigen::Matrix<double, -1, -1>(N, N);
      stan::math::fill(LobsCov, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 27;
      assign(LobsCov, nil_index_list(), multiply(L, obsCov),
        "assigning variable LobsCov");
      current_statement__ = 28;
      validate_non_negative_index("nugget", "N", N);
      current_statement__ = 29;
      validate_non_negative_index("parCov", "N", N);
      current_statement__ = 30;
      validate_non_negative_index("parCov", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += N;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_space_oneK_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha0;
      alpha0 = DUMMY_VAR__;
      
      current_statement__ = 1;
      alpha0 = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        alpha0 = stan::math::lb_constrain(alpha0, 0, lp__);
      } else {
        current_statement__ = 1;
        alpha0 = stan::math::lb_constrain(alpha0, 0);
      }
      local_scalar_t__ alphaD;
      alphaD = DUMMY_VAR__;
      
      current_statement__ = 2;
      alphaD = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        alphaD = stan::math::lb_constrain(alphaD, 0, lp__);
      } else {
        current_statement__ = 2;
        alphaD = stan::math::lb_constrain(alphaD, 0);
      }
      local_scalar_t__ alpha2;
      alpha2 = DUMMY_VAR__;
      
      current_statement__ = 3;
      alpha2 = in__.scalar();
      current_statement__ = 3;
      if (jacobian__) {
        current_statement__ = 3;
        alpha2 = stan::math::lub_constrain(alpha2, 0, 2, lp__);
      } else {
        current_statement__ = 3;
        alpha2 = stan::math::lub_constrain(alpha2, 0, 2);
      }
      local_scalar_t__ gamma;
      gamma = DUMMY_VAR__;
      
      current_statement__ = 4;
      gamma = in__.scalar();
      current_statement__ = 4;
      if (jacobian__) {
        current_statement__ = 4;
        gamma = stan::math::lb_constrain(gamma, 0, lp__);
      } else {
        current_statement__ = 4;
        gamma = stan::math::lb_constrain(gamma, 0);
      }
      Eigen::Matrix<local_scalar_t__, -1, 1> nugget;
      nugget = Eigen::Matrix<local_scalar_t__, -1, 1>(N);
      stan::math::fill(nugget, DUMMY_VAR__);
      
      current_statement__ = 5;
      nugget = in__.vector(N);
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 5;
        if (jacobian__) {
          current_statement__ = 5;
          assign(nugget, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(nugget[(sym1__ - 1)], 0, lp__),
            "assigning variable nugget");
        } else {
          current_statement__ = 5;
          assign(nugget, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(nugget[(sym1__ - 1)], 0),
            "assigning variable nugget");
        }}
      Eigen::Matrix<local_scalar_t__, -1, -1> parCov;
      parCov = Eigen::Matrix<local_scalar_t__, -1, -1>(N, N);
      stan::math::fill(parCov, DUMMY_VAR__);
      
      current_statement__ = 7;
      assign(parCov, nil_index_list(),
        spCov(N, alpha0, alphaD, alpha2, geoDist, nugget, gamma, pstream__),
        "assigning variable parCov");
      {
        current_statement__ = 8;
        lp_accum__.add(normal_lpdf<propto__>(alpha0, 0, 1));
        current_statement__ = 9;
        lp_accum__.add(normal_lpdf<propto__>(alphaD, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(uniform_lpdf<propto__>(alpha2, 0, 2));
        current_statement__ = 11;
        lp_accum__.add(normal_lpdf<propto__>(nugget, 0, 1));
        current_statement__ = 12;
        lp_accum__.add(normal_lpdf<propto__>(gamma, varMeanFreqs, 0.5));
        current_statement__ = 13;
        lp_accum__.add(wishart_lpdf<propto__>(LobsCov, L, parCov));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_space_oneK_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double alpha0;
      alpha0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha0 = in__.scalar();
      current_statement__ = 1;
      alpha0 = stan::math::lb_constrain(alpha0, 0);
      double alphaD;
      alphaD = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      alphaD = in__.scalar();
      current_statement__ = 2;
      alphaD = stan::math::lb_constrain(alphaD, 0);
      double alpha2;
      alpha2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      alpha2 = in__.scalar();
      current_statement__ = 3;
      alpha2 = stan::math::lub_constrain(alpha2, 0, 2);
      double gamma;
      gamma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      gamma = in__.scalar();
      current_statement__ = 4;
      gamma = stan::math::lb_constrain(gamma, 0);
      Eigen::Matrix<double, -1, 1> nugget;
      nugget = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(nugget, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      nugget = in__.vector(N);
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 5;
        assign(nugget, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(nugget[(sym1__ - 1)], 0),
          "assigning variable nugget");}
      Eigen::Matrix<double, -1, -1> parCov;
      parCov = Eigen::Matrix<double, -1, -1>(N, N);
      stan::math::fill(parCov, std::numeric_limits<double>::quiet_NaN());
      
      vars__.emplace_back(alpha0);
      vars__.emplace_back(alphaD);
      vars__.emplace_back(alpha2);
      vars__.emplace_back(gamma);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(nugget[(sym1__ - 1)]);}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      assign(parCov, nil_index_list(),
        spCov(N, alpha0, alphaD, alpha2, geoDist, nugget, gamma, pstream__),
        "assigning variable parCov");
      if (emit_transformed_parameters__) {
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            vars__.emplace_back(
              rvalue(parCov,
                cons_list(index_uni(sym2__),
                  cons_list(index_uni(sym1__), nil_index_list())), "parCov"));
          }}
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double alpha0;
      alpha0 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha0 = context__.vals_r("alpha0")[(1 - 1)];
      double alpha0_free__;
      alpha0_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      alpha0_free__ = stan::math::lb_free(alpha0, 0);
      double alphaD;
      alphaD = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      alphaD = context__.vals_r("alphaD")[(1 - 1)];
      double alphaD_free__;
      alphaD_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      alphaD_free__ = stan::math::lb_free(alphaD, 0);
      double alpha2;
      alpha2 = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      alpha2 = context__.vals_r("alpha2")[(1 - 1)];
      double alpha2_free__;
      alpha2_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 3;
      alpha2_free__ = stan::math::lub_free(alpha2, 0, 2);
      double gamma;
      gamma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      gamma = context__.vals_r("gamma")[(1 - 1)];
      double gamma_free__;
      gamma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      gamma_free__ = stan::math::lb_free(gamma, 0);
      Eigen::Matrix<double, -1, 1> nugget;
      nugget = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(nugget, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> nugget_flat__;
        current_statement__ = 5;
        assign(nugget_flat__, nil_index_list(), context__.vals_r("nugget"),
          "assigning variable nugget_flat__");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 5;
          assign(nugget, cons_list(index_uni(sym1__), nil_index_list()),
            nugget_flat__[(pos__ - 1)], "assigning variable nugget");
          current_statement__ = 5;
          pos__ = (pos__ + 1);}
      }
      Eigen::Matrix<double, -1, 1> nugget_free__;
      nugget_free__ = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(nugget_free__, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 5;
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        current_statement__ = 5;
        assign(nugget_free__, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(nugget[(sym1__ - 1)], 0),
          "assigning variable nugget_free__");}
      vars__.emplace_back(alpha0_free__);
      vars__.emplace_back(alphaD_free__);
      vars__.emplace_back(alpha2_free__);
      vars__.emplace_back(gamma_free__);
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(nugget_free__[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("alpha0");
    names__.emplace_back("alphaD");
    names__.emplace_back("alpha2");
    names__.emplace_back("gamma");
    names__.emplace_back("nugget");
    names__.emplace_back("parCov");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha0");
    param_names__.emplace_back(std::string() + "alphaD");
    param_names__.emplace_back(std::string() + "alpha2");
    param_names__.emplace_back(std::string() + "gamma");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "nugget" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "parCov" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha0");
    param_names__.emplace_back(std::string() + "alphaD");
    param_names__.emplace_back(std::string() + "alpha2");
    param_names__.emplace_back(std::string() + "gamma");
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "nugget" + '.' + std::to_string(sym1__));
      }}
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "parCov" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alphaD\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nugget\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"parCov\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"alpha0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alphaD\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"alpha2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nugget\",\"type\":{\"name\":\"vector\",\"length\":" << N << "},\"block\":\"parameters\"},{\"name\":\"parCov\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << N << "},\"block\":\"transformed_parameters\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_space_oneK_namespace::model_space_oneK;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_space_oneK_namespace::profiles__;
}
#endif
#endif
